name: k6 Performance Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install k6
        run: |
          sudo gpg -k
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Build TypeScript
        run: npm run build

      - name: Run performance test and export JSON
        run: k6 run --summary-export summary.json dist/randomUsers.test.js

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: k6-performance-report
          path: summary.html

      - name: Extract metrics and publish summary
        run: |
          AVG=$(jq '.metrics.http_req_duration.avg' summary.json)
          P95=$(jq '.metrics.http_req_duration["p(95)"]' summary.json)
          FAIL_RATE=$(jq '.metrics.http_req_failed.rate' summary.json)
          REQS=$(jq '.metrics.http_reqs.count' summary.json)

          echo "## k6 Performance Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|------|------|" >> $GITHUB_STEP_SUMMARY
          echo "| Avg request duration | ${AVG} ms |" >> $GITHUB_STEP_SUMMARY
          echo "| P95 request duration | ${P95} ms |" >> $GITHUB_STEP_SUMMARY
          echo "| Failed requests | ${FAIL_RATE} |" >> $GITHUB_STEP_SUMMARY
          echo "| Total requests | ${REQS} |" >> $GITHUB_STEP_SUMMARY